### ISSUE TITLE
Some functions not displaying complete parameters and return values

### ISSUE THREAD

**Issue by brucify** [erldocs/erldocs.com#4]
Some functions are not displaying correctly. For example, instead of 
```erlang
keysearch/3
1..tuple_size(Tuple)
```
the correct display should be
```erlang
keysearch(Key, N, TupleList) -> {value, Tuple}
```

Example: `lists:keysearch` 
On erldocs.com: http://erldocs.com/18.1/stdlib/lists.html?i=4&search=keysear#keysearch/3
```erlang
keysearch/3
1..tuple_size(Tuple)
```

It is because their XML file has a special format: https://github.com/erlang/otp/blob/maint/lib/stdlib/doc/src/lists.xml#L348
```xml
<func>
      <name name="keysearch" arity="3"/> 
...
```
The correct information must be fetched from the .erl source at 
https://github.com/erlang/otp/blob/OTP-18.0/lib/stdlib/src/lists.erl#L68-L72
```erlang
-spec keysearch(Key, N, TupleList) -> {value, Tuple} | false when
      Key :: term(),
      N :: pos_integer(),
      TupleList :: [Tuple],
      Tuple :: tuple().
```

However, some functions are working correctly because their xml is written in a different way.

Example: `inets:start`
On erldocs.com: http://erldocs.com/18.1/inets/inets.html?i=2&search=inets:start#start/2
```erlang
start(Service, ServiceConfig) -> {ok, Pid} | {error, Reason}
```

Because their XML file contains this information: https://github.com/erlang/otp/blob/maint/lib/inets/doc/src/inets.xml#L123
```xml
<func>
      <name>start(Service, ServiceConfig) -> {ok, Pid} | {error, Reason}</name>
```

**Comment by fenollp** [comment]
This is probably related : https://github.com/erldocs/erldocs/issues/22

**Comment by brucify** [comment]
Posted to https://github.com/erldocs/erldocs/issues/28 instead
