### ISSUE TITLE
Some non-public modules and functions should not be displayed

### ISSUE THREAD

**Issue by brucify** [erldocs/erldocs.com#5]
Only the public modules and functions should be displayed. 

For example the application `asn1` should only have two displayed modules `asn1ct` and `asn1rt`:
http://erlang.org/doc/man/asn1ct.html

But on erldocs.com, many non-public modules are visible, which is confusing:
http://erldocs.com/current/index.html?i=0&search=asn1#asn1

**Possible solution (Recommended)**:
For example, the application `asn1` has two publicly visible modules: `asn1ct` and `asn1rt`. They are located at:
`lib/asn1/doc/src/asn1ct.xml`
https://github.com/erlang/otp/tree/maint/lib/asn1/doc/src/asn1ct.xml
`lib/asn1/doc/src/asn1rt.xml`
https://github.com/erlang/otp/tree/maint/lib/asn1/doc/src/asn1rt.xml

Getting the module info of `asn1rt` from `lib/asn1/doc/src/asn1rt.xml`: 
https://github.com/erlang/otp/blob/maint/lib/asn1/doc/src/asn1rt.xml#L35-L44
```xml
  <module>asn1rt</module>
  <modulesummary>ASN.1 runtime support functions</modulesummary>
  <description>
    <warning>
      <p>
	All functions in this module are deprecated and will be
	removed in a future release.
      </p>
    </warning>
  </description>
```

All the functions in this file are public.
```xml
  <funcs>
    <func>
        ...
    </func>
    ...
  </funcs>
```
Getting the function info from `lib/asn1/doc/src/asn1rt.xml`:
https://github.com/erlang/otp/blob/maint/lib/asn1/doc/src/asn1rt.xml#L63-L81
```xml
    <func>
      <name>encode(Module,Type,Value)-> {ok,Bytes} | {error,Reason}</name>
      <fsummary>Encodes an ASN.1 value.</fsummary>
      <type>
        <v>Module = Type = atom()</v>
        <v>Value = term()</v>
        <v>Bytes = binary</v>
        <v>Reason = term()</v>
      </type>
      <desc>
        <p>Encodes <c>Value</c> of <c>Type</c> defined in the <c>ASN.1</c>
        module <c>Module</c>. Returns a binary if successful. To get
        as fast execution as possible, the encode function performs
        only the rudimentary test that input <c>Value</c> is a correct
        instance of <c>Type</c>. For example, the length of strings is
        not always checked.</p>
	<p>Use <c>Module:encode(Type, Value)</c> instead of this function.</p>
      </desc>
    </func>
```

See also comment from Kenneth Lundin from OTP team:
http://erlang.org/pipermail/erlang-questions/2015-May/084638.html

"The majority of modules are not intended to be used outside their applications and thus they have no public API. "

Updated 2015-11-13 13:25 CET

**Comment by fenollp** [comment]
Could you inquire about how these `.eix` files are generated?
Is there a list of “exported modules” smoewhere in OTP?

**Comment by brucify** [comment]
Updated the description. Recommend solution 1. Retrieving from XML files instead of `.eix` files

**Comment by brucify** [comment]
Closed and reposted to erldocs repo.
